COMMAND=emu
HANDLER=resources/emulator/handler.sh
TITLE="Exclusive Android emulator leases (default pool: 2; phone/API 36)"
ACTION="catalog catalog read-only not-needed"
ACTION="status status read-only not-needed"
ACTION="run run session not-needed"
ACTION="acquire acquire bounded-write not-needed"
ACTION="renew renew bounded-write not-needed"
ACTION="release release bounded-write not-needed"
ACTION="cache cache bounded-write not-needed"
ACTION="view view session not-needed"
ACTION="revoke revoke shared-workload-change reversible"
ACTION="down down shared-workload-change reversible"
BRINGUP=status
SHUTDOWN=down
