#!/usr/bin/env python3
"""Capture public command help using an isolated, public-only repository."""

import argparse
import os
from pathlib import Path
import shutil
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the reference is stale")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    binary = root / ".build/yard"
    if not binary.is_file():
        parser.error("build the current CLI with make build first")

    sections = [
        "# CLI reference\n\n"
        "Generated by `make cli-docs` from the public command registry and actual "
        "`yard <command> --help` output. Do not edit this file directly.\n\n"
        "Options belong to the invocations shown in each help block; a flag for one "
        "subcommand is not automatically valid for another. Profile resource commands "
        "provide their own help through `yard <resource> --help`.\n"
    ]
    with tempfile.TemporaryDirectory(prefix="subyard-cli-docs-") as temporary:
        sandbox = Path(temporary)
        public = sandbox / "repository"
        for name in ("config", "scripts"):
            shutil.copytree(root / name, public / name)
        home = sandbox / "home"
        home.mkdir(mode=0o700)
        environment = {
            "PATH": os.defpath,
            "HOME": str(home),
            "SUBYARD_REPOSITORY_ROOT": str(public),
            "SUBYARD_CONFIG_HOME": str(home / ".config/subyard"),
            "SUBYARD_NO_AUDIT": "1",
            "LC_ALL": "C",
        }
        for line in (public / "config/commands.registry").read_text().splitlines():
            if not line or line.startswith("#"):
                continue
            fields = line.split("|")
            if fields[7] != "public":
                continue
            name, summary = fields[0], fields[11]
            result = subprocess.run(
                [str(binary), name, "--help"], cwd=public, env=environment,
                stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=15,
            )
            if result.returncode or result.stderr or not result.stdout.strip():
                parser.error(f"yard {name} --help failed: {result.stderr.strip()}")
            help_text = result.stdout.strip()
            if temporary in help_text:
                parser.error(f"yard {name} --help contains environment-specific paths")
            sections.append(f"\n## {name}\n\n{summary}.\n\n```text\n{help_text}\n```\n")

    output = root / "docs/cli-reference.md"
    content = "".join(sections)
    if args.check:
        if not output.exists() or output.read_text() != content:
            parser.error("CLI reference is stale; run make cli-docs")
    else:
        output.write_text(content)


if __name__ == "__main__":
    main()
