#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="$ROOT/config/profiles/openclaw/provision.sh"
tmp="$(mktemp -d)"
trap 'rm -rf -- "$tmp"' EXIT
test_root="$tmp/root"
dev_home="$tmp/home"
mkdir -p "$test_root/usr/local/bin" "$test_root/opt/venv/bin" \
  "$test_root/srv/cache/pnpm" "$test_root/srv/cache/pip" "$test_root/srv/cache/npm" \
  "$test_root/etc/profile.d" "$test_root/etc/subyard" "$dev_home/.config/pip"

cat > "$test_root/usr/local/bin/node" <<'NODE'
#!/usr/bin/env bash
printf 'v24.15.0\n'
NODE
cat > "$test_root/usr/local/bin/corepack" <<'COREPACK'
#!/usr/bin/env bash
printf '0.31.0\n'
COREPACK
cat > "$test_root/usr/local/bin/pnpm" <<'PNPM'
#!/usr/bin/env bash
printf '11.2.2\n'
PNPM
cat > "$test_root/usr/local/bin/sy-cache" <<'CACHE'
#!/usr/bin/env bash
exit 0
CACHE
cat > "$test_root/opt/venv/bin/python" <<'PYTHON'
#!/usr/bin/env bash
exit 0
PYTHON
cat > "$test_root/opt/venv/bin/pip" <<'PIP'
#!/usr/bin/env bash
exit 0
PIP
chmod +x "$test_root/usr/local/bin/"* "$test_root/opt/venv/bin/"*

cat > "$dev_home/.npmrc" <<'NPMRC'
# >>> subyard-openclaw >>>
cache=/srv/cache/npm
# <<< subyard-openclaw <<<
NPMRC
cat > "$dev_home/.config/pip/pip.conf" <<'PIPCONF'
# GENERATED by Subyard openclaw provision.sh — shared pip cache.
[global]
cache-dir = /srv/cache/pip
PIPCONF
printf 'export SUBYARD_OPENCLAW_DOCS=/etc/subyard/openclaw-l1.md\n' \
  > "$test_root/etc/profile.d/subyard-openclaw.sh"
cat > "$test_root/etc/environment" <<'ENVIRONMENT'
# >>> subyard-openclaw >>>
SUBYARD_OPENCLAW_DOCS=/etc/subyard/openclaw-l1.md
# <<< subyard-openclaw <<<
ENVIRONMENT
printf '# OpenClaw in this yard — L1 build / test / live (self-serve)\n' \
  > "$test_root/etc/subyard/openclaw-l1.md"

common_env=(
  OPENCLAW_TEST_ROOT="$test_root"
  OPENCLAW_DEV_HOME="$dev_home"
  OPENCLAW_TEST_ALLOW_NON_ROOT=1
  DEV_USER="$(id -un)"
  PIP_CACHE_DIR=/srv/cache/pip
  npm_config_cache=/srv/cache/npm
  npm_config_store_dir=/srv/cache/pnpm
)

before="$(find "$tmp" -type f -exec sha256sum {} + | sort | sha256sum)"
env "${common_env[@]}" bash "$HOOK" --check >/dev/null
after="$(find "$tmp" -type f -exec sha256sum {} + | sort | sha256sum)"
[ "$before" = "$after" ] || { printf 'FAIL: OpenClaw check mutated state\n' >&2; exit 1; }

sed -i 's/v24\.15\.0/v0.0.0/' "$test_root/usr/local/bin/node"
set +e
env "${common_env[@]}" bash "$HOOK" --check >/dev/null
status=$?
set -e
[ "$status" -eq 10 ] || { printf 'FAIL: OpenClaw drift status=%s, want 10\n' "$status" >&2; exit 1; }

printf 'ok: OpenClaw provision check\n'
