package projectruntime

import (
	"context"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Subyard/Subyard/internal/adapters/transport"
	"github.com/Subyard/Subyard/internal/shellquote"
	"github.com/Subyard/Subyard/internal/testkit"
)

func TestVSCodeUpgradesLegacyManagedSSHWithoutChangingTransport(t *testing.T) {
	for _, proxy := range []string{"", "    ProxyJump fixture-owner\n"} {
		t.Run(strings.TrimSpace(proxy), func(t *testing.T) {
			code, snippet, called := codeSSHFixture(t)
			original := "# Managed by Subyard; regenerated by 'yard remote add'.\n" +
				"Host yard-fixture\n    HostName 127.0.0.1\n    Port 2233\n    User fixture\n" + proxy +
				"    IdentityFile /fixture/identity\n    IdentitiesOnly yes\n" +
				"    HostKeyAlias fixture-pin\n    StrictHostKeyChecking yes\n" +
				"    ControlPath ~/.ssh/subyard-cm-%C\n    ControlPersist 60s\n"
			testkit.WriteFile(t, snippet, []byte(original), 0o600)
			if _, err := code.Run(context.Background(), "/fixture/Demo.code-workspace"); err != nil {
				t.Fatal(err)
			}
			arguments, err := os.ReadFile(called)
			if err != nil || string(arguments) != "/fixture/Demo.code-workspace\n" {
				t.Fatalf("workspace was not opened: arguments=%q err=%v", arguments, err)
			}
			updated, err := os.ReadFile(snippet)
			if err != nil {
				t.Fatal(err)
			}
			_, originalBody, _ := strings.Cut(original, "\n")
			if !strings.Contains(string(updated), strings.Replace(originalBody, "Host yard-fixture\n", "Host yard-fixture yard-fixture.code\n", 1)) {
				t.Fatal("migration changed the existing transport or host-key pins")
			}
			for _, host := range []string{code.SSHHost, code.CodeSSHHost} {
				output, err := exec.Command("ssh", "-G", host).Output()
				if err != nil {
					t.Fatal(err)
				}
				options := string(output)
				for _, option := range []string{"hostname 127.0.0.1\n", "port 2233\n", "user fixture\n", "hostkeyalias fixture-pin\n", "identityfile /fixture/identity\n"} {
					if !strings.Contains(options, option) {
						t.Fatalf("SSH route %s lost %q", host, option)
					}
				}
				if host == code.SSHHost && strings.Contains(options, "localforward ") {
					t.Fatal("ordinary SSH alias gained a preview forward")
				}
			}
			if _, err := code.Run(context.Background(), "/fixture/Demo.code-workspace"); err != nil {
				t.Fatal(err)
			}
			after, _ := os.ReadFile(snippet)
			info, _ := os.Stat(snippet)
			if string(after) != string(updated) || info.Mode().Perm() != 0o600 {
				t.Fatal("repeated launch changed the snippet or its private mode")
			}
		})
	}
}

func TestVSCodeRejectsUnavailableAliasBeforeLaunch(t *testing.T) {
	for _, state := range []string{"unmanaged", "missing-include", "symlink"} {
		t.Run(state, func(t *testing.T) {
			code, snippet, called := codeSSHFixture(t)
			payload := "# Managed by Subyard\nHost yard-fixture\n    HostName 127.0.0.1\n"
			switch state {
			case "unmanaged":
				payload = strings.TrimPrefix(payload, "# Managed by Subyard\n")
			case "missing-include":
				testkit.WriteFile(t, filepath.Join(code.Home, ".ssh", "config"), nil, 0o600)
			case "symlink":
				target := filepath.Join(testkit.TempDir(t), "protected")
				testkit.WriteFile(t, target, []byte(payload), 0o600)
				if err := os.Symlink(target, snippet); err != nil {
					t.Fatal(err)
				}
			}
			if state != "symlink" {
				testkit.WriteFile(t, snippet, []byte(payload), 0o600)
			}
			if _, err := code.Run(context.Background(), "/fixture/Demo.code-workspace"); err == nil || !strings.Contains(err.Error(), "SSH alias") {
				t.Fatalf("unavailable alias was accepted: %v", err)
			}
			if _, err := os.Stat(called); !os.IsNotExist(err) {
				t.Fatalf("VS Code launched with an unavailable alias: %v", err)
			}
			after, _ := os.ReadFile(snippet)
			if string(after) != payload {
				t.Fatal("unavailable configuration was changed")
			}
		})
	}
}

func codeSSHFixture(t *testing.T) (VSCode, string, string) {
	t.Helper()
	ssh, err := exec.LookPath("ssh")
	if err != nil {
		t.Fatal(err)
	}
	home := testkit.TempDir(t)
	directory := filepath.Join(home, ".ssh")
	if err := os.Mkdir(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	snippet := filepath.Join(directory, "subyard-fixture.config")
	configuration := filepath.Join(directory, "config")
	testkit.WriteFile(t, configuration, []byte("Include "+snippet+"\n"), 0o600)
	bin := testkit.TempDir(t)
	testkit.WriteFile(t, filepath.Join(bin, "ssh"), []byte("#!/bin/sh\nexec "+shellquote.Command([]string{ssh, "-F", configuration})+" \"$@\"\n"), 0o700)
	called := filepath.Join(home, "code.called")
	program := filepath.Join(bin, "code")
	testkit.WriteFile(t, program, []byte("#!/bin/sh\nprintf '%s\\n' \"$@\" > "+shellquote.Word(called)+"\n"), 0o700)
	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))
	return VSCode{Process: transport.Process{Program: program, Env: os.Environ()}, Home: home, SSHHost: "yard-fixture", CodeSSHHost: "yard-fixture.code"}, snippet, called
}

func TestPreviewPortPreflightRejectsBusyListener(t *testing.T) {
	listener, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer listener.Close()
	address := listener.Addr().String()
	err = previewPortAvailable(address)
	if err == nil || !strings.Contains(err.Error(), address) {
		t.Fatalf("busy port accepted: err=%v", err)
	}
	if err := listener.Close(); err != nil {
		t.Fatal(err)
	}
	if err := previewPortAvailable(address); err != nil {
		t.Fatalf("free port rejected: err=%v", err)
	}
}
