#!/usr/bin/env bash
# Typed context boundary between the Go engine and physical Shell adapters.

[ -n "${SUBYARD_ENGINE_CONTEXT_SOURCED:-}" ] && return 0
SUBYARD_ENGINE_CONTEXT_SOURCED=1

subyard_context_error() {
  printf 'subyard adapter: %s\n' "$*" >&2
  exit 2
}

subyard_require_engine_context() {
  [ "${SUBYARD_ENGINE_CONTEXT:-}" = 1 ] \
    || subyard_context_error "prepared engine context required"
  [ "${SUBYARD_ENGINE_CONTEXT_SCHEMA:-}" = 1 ] \
    || subyard_context_error "unsupported engine context schema"

  local name
  for name in SUBYARD_OPERATOR_HOME SUBYARD_CONFIG_DIR SUBYARD_CONFIG_HOME SUBYARD_HOME \
    STORAGE_PATH HOST_BASE RESTRICTED_DISK_PATHS ACCESS_KIND YARD_KIND YARD_INSTANCE_NAME \
    INCUS_PROJECT INCUS_BRIDGE SSH_HOST DEV_USER DEV_UID DEV_SUDO FORWARD_SSH_AGENT \
    NESTED_E2E_VMS; do
    [ -n "${!name+x}" ] || subyard_context_error "engine context is missing $name"
  done
}

path_is_broad_host_root() {
  local path="$1" operator_home="${SUBYARD_OPERATOR_HOME:-}"
  case "$path" in
    / | /boot | /dev | /etc | /home | /opt | /proc | /root | /run | /srv | /sys | /usr | /var)
      return 0
      ;;
  esac
  [ -n "$operator_home" ] && [ "$path" = "$operator_home" ]
}

subyard_elevated_context() {
  local name root_home
  root_home="$(getent passwd root 2>/dev/null | cut -d: -f6 || true)"
  [ -n "$root_home" ] || root_home=/root
  SUBYARD_ELEVATED_ENV=(
    "HOME=$root_home"
    "SUBYARD_ELEVATED=1"
    "SUBYARD_ENGINE_CONTEXT=1"
    "SUBYARD_ENGINE_CONTEXT_SCHEMA=1"
  )
  for name in \
    ASSUME_YES PROG YARD_ENGINE YARD_VERSION \
    SUBYARD_USER SUBYARD_OPERATOR_HOME SUBYARD_CONFIG_DIR SUBYARD_CONFIG_HOME SUBYARD_HOME \
    SUBYARD_CONFIG_SHARED_DIR SUBYARD_CONFIG_HOST_DIR SUBYARD_CONFIG_YARD_DIR \
    SUBYARD_CONFIG_GENERATED_DIR \
    SUBYARD_STATE_DIR SUBYARD_YARD SUBYARD_YARD_EXPLICIT SUBYARD_DISPATCHER_PATH \
    SUBYARD_SUDO_PREAUTHORIZED \
    SUBYARD_POWER_ENGINE_SOURCE SUBYARD_POWER_LIBEXEC_DIR SUBYARD_POWER_RECONCILER_PATH \
    SUBYARD_POWER_UNIT_PATH SUBYARD_POWER_DESIRED SUBYARD_TEARDOWN_KEEP_DATA \
    SUBYARD_TEST_VMS_SINK_ENGINE_SOURCE SUBYARD_TEST_VMS_SINK_LIBEXEC_DIR \
    SUBYARD_TEST_VMS_SINK_PATH SUBYARD_TEST_VMS_SINK_SERVICE_PATH \
    SUBYARD_TEST_VMS_SINK_TIMER_PATH \
    SUBYARD_TEARDOWN_KEEP_SHARED \
    SUBYARD_KEYS_CONSUMER_ROOT SUBYARD_KEYS_ROOT SUBYARD_KEYS_RUNTIME_DIR \
    SUBYARD_KEYS_SYSTEMD_DIR SUBYARD_KEYS_SYSTEMD_SKIP_ENABLE SUBYARD_KEYS_TOOLS_DIR \
    YARD_RUNTIME_ROOT YARD_NAME ACCESS_KIND YARD_TEMPLATE ENVIRONMENT_PROFILES \
    YARD_KIND YARD_INSTANCE_NAME INCUS_PROJECT INCUS_BRIDGE INCUS_NETWORK \
    SSH_HOST SSH_PORT DEV_USER DEV_UID DEV_SUDO FORWARD_SSH_AGENT SHIFT_MODE \
    NESTED_E2E_VMS E2E_VM_IMAGE E2E_VM_CPU E2E_VM_MEMORY E2E_VM_DISK \
    E2E_VM_SLOT_COUNT E2E_VM_BOOT_TIMEOUT E2E_BROKER_SOURCE \
    STORAGE_PATH STORAGE_POOL HOST_BASE HOST_LINKS HOST_MOUNTS RESTRICTED_DISK_PATHS \
    SRV_POOL SRV_VOLUME LIMITS_CPU LIMITS_MEMORY \
    YARD_CAPABILITIES YARD_CAPS YARD_DEVICES YARD_MOUNTS \
    SUBYARD_EXTRAS_MOUNTS SUBYARD_EXTRAS_CAPABILITIES SUBYARD_EXTRAS_DEVICES \
    YARD_IMAGE YARD_IMAGE_FALLBACK \
    HOST_CLAUDE_MD HOST_CODEX_AGENTS_MD HOST_OPENCODE_AGENTS_MD \
    CODING_TOOL_INTEGRATIONS CCUSAGE_PROVISION CCUSAGE_VERSION CCUSAGE_SHA256_AMD64 CCUSAGE_SHA256_ARM64 \
    CODEX_VERSION CODEX_SHA256_AMD64 CODEX_SHA256_ARM64 \
    SUBYARD_AGE_VERSION SUBYARD_AGE_SHA256_AMD64 SUBYARD_AGE_SHA256_ARM64 \
    SUBYARD_SOPS_VERSION SUBYARD_SOPS_SHA256_AMD64 SUBYARD_SOPS_SHA256_ARM64 \
    SUBYARD_PREFLIGHT_STRICT SUBYARD_PREFLIGHT_BASE_PRESENT MIN_DISK_GIB \
    RESUME_MIN_DISK_GIB REC_DISK_GIB MIN_INCUS_VER; do
    [ -z "${!name+x}" ] || SUBYARD_ELEVATED_ENV+=("$name=${!name}")
  done

  while IFS= read -r name; do
    case "$name" in
      AGENT_*_CHECK | AGENT_*_COMMAND | AGENT_*_CONFIG | AGENT_*_CONFIG_DEST | \
        AGENT_*_DEPENDS | AGENT_*_PERSIST | AGENT_*_PROJECTS_CHANGED | AGENT_*_PROVISION | \
        AGENT_*_RULES | AGENT_*_RULES_DEST)
        SUBYARD_ELEVATED_ENV+=("$name=${!name}")
        ;;
    esac
  done < <(compgen -A variable AGENT_ | sort -u)
}
