COMMAND=vpn
HANDLER=resources/vpn/handler.sh
TITLE="Amnezia VPN network"
PROXY="amnezia-vpn RESOURCE_VPN_IPV4 RESOURCE_VPN_PORT RESOURCE_VPN_INTERFACE udp:guest:host-port owner-metadata-v1 owner-ipv4-udp"
ACTION="up up public-ingress-change reversible"
ACTION="down down public-ingress-change reversible"
ACTION="status status read-only not-needed"
ACTION="is-up is-up read-only not-needed"
BRINGUP=up
SHUTDOWN=down
STARTUP=bringup
